apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "k8s-dashboard-agent.fullname" . }}
  labels:
    {{- include "k8s-dashboard-agent.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "k8s-dashboard-agent.selectorLabels" . | nindent 6 }}
