replicaCount: 1

image:
  repository: dhruvmistry200/kubepulse-agent
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Dashboard connection settings (required — set these during helm install)
registrationToken: ""
dashboardUrl: ""
clusterName: ""

nameOverride: ""
